namespace ZotapaySDK.Models.Payout
{
    using System.Runtime.Serialization;
    using ZotapaySDK.Contracts;

    public class MGPayoutData : IData
    {
        /// <summary>
        /// Order unique identifier generated by Zotapay.
        /// </summary>
        [DataMember(Name = "orderID", EmitDefaultValue = false)]
        public string orderID { get; set; }

        /// <summary>
        /// Merchant-defined unique order identifier.
        /// </summary>
        [DataMember(Name = "merchantOrderID", EmitDefaultValue = false)]
        public string merchantOrderID { get; set; }
    }
}
