namespace ZotapaySDK.Models.Deposit
{
    using System.Runtime.Serialization;
    using ZotapaySDK.Contracts;

    /// <summary>
    /// Direct card deposits will happen "synchronously", hence there will be no deposit url in the response
    /// </summary>
    public class DepositCardResponseData : IData
    {
        /// <summary>
        /// The status of the requested payment (e.g PROCESSING).
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Merchants' order unique identifier, provided in the original Deposit Request.
        /// </summary>
        [DataMember(Name = "merchantOrderID", EmitDefaultValue = false)]
        public string MerchantOrderID { get; set; }

        /// <summary>
        /// Order unique identifier generated by Zotapay, should be then used for Order Status Requests.
        /// </summary>
        [DataMember(Name = "orderID", EmitDefaultValue = false)]
        public string OrderID { get; set; }
    }
}
