namespace ZotapaySDK.Models.OrderStatusCheck
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Net.Http;
    using System.Runtime.Serialization;
    using System.Security.Cryptography;
    using System.Text;
    using ZotapaySDK.Contracts;
    using ZotapaySDK.Static;
    using static ZotapaySDK.Static.Constants;

    /// <summary>
    /// Order status check request, as per https://doc.zotapay.com/deposit/1.0/#order-status-request
    /// </summary>
    public class MGQueryTxnRequest : IMGRequest
    {
        /// <summary>
        /// Default constructor will auto-set timestamp parameter
        /// </summary>
        public MGQueryTxnRequest()
        {
            Int32 ts = (Int32)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
            this.Timestamp = ts.ToString();
        }

        /// <summary>
        /// Unique merchant identifier provided by Zotapay (see https://doc.zotapay.com/deposit/1.0/#before-you-begin section)
        /// </summary>
        [Required, StringLength(32, MinimumLength = 2)]
        [DataMember(Name = "merchantID")]
        private string MerchantId { get; set; }

        /// <summary>
        /// Order unique identifier generated by Zotapay
        /// </summary>
        [Required, StringLength(128, MinimumLength = 2)]
        [DataMember(Name = "orderID")]
        public string OrderID { get; set; }

        /// <summary>
        /// Merchant-defined unique order identifier
        /// </summary>
        [Required, StringLength(128, MinimumLength = 2)]
        [DataMember(Name = "merchantOrderID")]
        public string MerchantOrderID { get; set; }

        /// <summary>
        /// Unix timestamp of the request time - will be auto set
        /// </summary>
        [Required, StringLength(15, MinimumLength = 2)]
        [DataMember(Name = "timestamp")]
        public string Timestamp { get; set; }

        /// <summary>
        /// Request checksum encrypted with SHA-256
        /// </summary>
        [StringLength(64, MinimumLength = 2)]
        [DataMember(Name = "signature")]
        public string Signature { get; set; }

        public void GenerateSignature(string endpointId, string secret)
        {
            // string to sign
            string toSign = $"{this.MerchantId}{this.MerchantOrderID}{this.OrderID}{this.Timestamp}{secret}";
            this.Signature = Hasher.ToSHA256(toSign);
        }

        public string GetRequestUrl(string baseUrl, string endpoint)
        {
            var domain = baseUrl + URL.PATH_STATUS_CHECK;
            var queryParams = $"?merchantID={this.MerchantId}&orderID={this.OrderID}&merchantOrderID={this.MerchantOrderID}&timestamp={this.Timestamp}&signature={this.Signature}";
            return domain + queryParams;
        }

        IMGResult IMGRequest.GetResultInstance()
        {
            return new MGQueryTxnResult();
        }

        void IMGRequest.SetupPrivateMembers(string merchantId)
        {
            this.MerchantId = merchantId;
        }

        HttpMethod IMGRequest.GetMethod()
        {
            return HttpMethod.Get;
        }
    }
}
