name: .NET Core Build

# More inspiration here:
# https://github.com/nogic1008/dotnet-ci-example/blob/master/.github/workflows/dotnetcore.yml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      config: 'Release'
    name: 'Build SDK' 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' 
     
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    # install dependencies  
    - name: NuGet Restore
      if: steps.cache.outputs.cache-hit != 'true'
      run: nuget restore ZotapaySDK.sln
      
    # build project
    - name: Build
      run: dotnet build --configuration ${{env.config}} --no-restore
      
    # run tests with built project
    - name: Test PR      
      run: |
        dotnet test --no-restore --no-build --configuration ${{env.config}} --logger GitHubActions

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
