name: .NET Core Build

# More inspiration here:
# https://github.com/nogic1008/dotnet-ci-example/blob/master/.github/workflows/dotnetcore.yml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: windows-latest
    env:
      config: 'Release'
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    dotnet: [ '2.1', '3.1', '5.0' ]
    #name: Test .NET ${{matrix.dotnet}}
    #steps:
    #- uses: actions/checkout@v2
    #- name: Setup .NET Core
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: ${{matrix.dotnet}}
    name: Test .NET Side by Side
    steps:
    - uses: actions/checkout@v2

    # Setup .NET frameworks
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '2.1'
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '3.1'
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '5.0'

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{matrix.dotnet}}-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{matrix.dotnet}}

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    # install dependencies 
    - name: NuGet Restore
      if: steps.cache.outputs.cache-hit != 'true'
      run: nuget restore ZotapaySDK.sln
      
    # build project
    - name: Build
      run: dotnet build --configuration ${{env.config}} --no-restore
      
    # run tests with built project
    - name: Test
      run: |
        dotnet test --framework netcoreapp2.1 --no-restore --no-build --configuration ${{env.config}} --logger GitHubActions
        dotnet test --framework netcoreapp3.1 --no-restore --no-build --configuration ${{env.config}}
        dotnet test --framework net5.0 --no-restore --no-build --configuration ${{env.config}}

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
