on:
  release:
    types: [published]
    paths-ignore:
      - 'README.md'
      - 'Tests/**'
      - 'Examples/**'

name: NuGet Package Release

permissions:
  contents: write
  packages: write
  actions: read
  checks: read
  pull-requests: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    name: NuGet Push
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: nuget restore

      - name: Build SDK
        run: dotnet build Zotapay --configuration Release --no-restore /p:Version=${{github.event.release.tag_name}}

      - name: Package
        run: dotnet pack --no-build --configuration Release Zotapay/Zotapay.csproj --output . /p:Version=${{github.event.release.tag_name}}

      - name: Push Package
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
